catalog:

catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    '@hono/vite-build': ^1.5.0
    '@hono/vite-dev-server': ^0.19.0
    eslint: ^9.22.0
    vercel: ^32.4.1
    vite: ^6.2.4
  framework:
    hono: ^4.7.5
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
