catalog:

catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    '@hono/node-server': ^1.14.0
    eslint: ^9.22.0
    esno: ^4.8.0
    vercel: ^41.4.1
    
  framework:
    hono: ^4.7.5
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
